### ISSUE TITLE
Does support drop down menus?

### ISSUE THREAD

**Issue by s3vus** [tomrutgers/middleman-starter-netlify-cms#9]
Does this theme have a built in way to have cascading drop down menus in the navigation?  I didn't see anything in the config but i'm not familiar with middleman. Just evaluating it.

**Comment by tomrutgers** [comment]
I'm sorry, I somehow missed this issue entirely. There's no support for drop down menus. This repo is not so much a theme as it is a means of trying out Netlify CMS and getting started with Middleman and Netlify CMS.
